name: "Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  Danger:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        id: action_id
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Danger
        run: yarn danger ci --failOnErrors
