name: "Pull Request"

on:
  pull_request:
    branches:
      - master

jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        id: action_id
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Danger
        run: yarn danger ci --failOnErrors
