name: Push Action

on: push

jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Commit Script
        run: node ../../script/commit.js --commit="${{github.event.commits}}"
      - name: Push Commit
        uses: actions/github-script@v5
        env:
          TEST_TOKEN: "test"
        with:
          script: |
            const fetch = require('node-fetch');
            const { TEST_TOKEN } = process.env;
            await fetch('${TEST_TOKEN}', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringfy({
                msgtype: 'markdown',
                markdown: {
                  `Commit Message: ${{join(github.event.commits.*.message, '\n')}}`
                }
              })
            });
