name: Push Action

on: push


jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Push Commit
        uses: actions/github-script@v5
        env: 
          TEST_TOKEN: 'test'
        with:
          script: |
            const fetch = require('node-fetch');
            const {TEST_TOKEN } = process.env;
            const commits =  ${{join(github.event.commits.*.message, ', ')}};
            await fetch('${TEST_TOKEN}', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringfy({
                msgtype: 'markdown',
                markdown: {
                  `Commit Message: ${commits}`
                }
              })
            });
