name: Push Action

on: push


jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Push Commit
        uses: actions/github-script@v5
        env: 
          TEST_TOKEN: 'test'
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const fetch = require('node-fetch');
            const {TEST_TOKEN, SHA } = process.env;
            const script = require('./path/to/script.js')
            const commit = await script({github, context, core})
            console.log('commits',$commit )
            console.log(context)
            echo context
            echo $commit
            await fetch('${TEST_TOKEN}', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringfy({
                msgtype: 'markdown',
                markdown: {
                  `Commit Message: ${{(github.event.commits.*.message).toString()}}`
                }
              })
            });
